<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAagFm76\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAagFm76/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAagFm76.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAagFm76\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAagFm76\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AagFm76',
    'container.build_id' => '17a936db',
    'container.build_time' => 1623342492,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAagFm76');
