<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'products' => [['cat_id'], ['cat_id' => null, '_controller' => 'App\\Controller\\EshopController::products'], [], [['variable', '/', '[^/]++', 'cat_id'], ['text', '/eshop/products']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\EshopController::register'], [], [['text', '/eshop/register']], [], []],
    'register_action' => [[], ['_controller' => 'App\\Controller\\EshopController::register_action'], [], [['text', '/eshop/register_action']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\EshopController::login'], [], [['text', '/eshop/login']], [], []],
    'login_action' => [[], ['_controller' => 'App\\Controller\\EshopController::login_action'], [], [['text', '/eshop/login_action']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\EshopController::logout'], [], [['text', '/eshop/logout']], [], []],
    'addProduct' => [['id', 'cat_id'], ['cat_id' => null, '_controller' => 'App\\Controller\\EshopController::add_product'], [], [['variable', '/', '[^/]++', 'cat_id'], ['variable', '/', '[^/]++', 'id'], ['text', '/eshop/add_product']], [], []],
    'checkout' => [[], ['_controller' => 'App\\Controller\\EshopController::checkout'], [], [['text', '/eshop/checkout']], [], []],
    'checkout_action' => [['id', 'action'], ['_controller' => 'App\\Controller\\EshopController::checkout_action'], [], [['variable', '/', '[^/]++', 'action'], ['variable', '/', '[^/]++', 'id'], ['text', '/eshop/checkout_action']], [], []],
    'order_action' => [[], ['_controller' => 'App\\Controller\\EshopController::order_action'], [], [['text', '/eshop/order_action']], [], []],
    'orders' => [[], ['_controller' => 'App\\Controller\\EshopController::orders'], [], [['text', '/eshop/orders']], [], []],
    'message' => [[], ['_controller' => 'App\\Controller\\EshopController::message'], [], [['text', '/eshop/message']], [], []],
];
